### ISSUE TITLE
Image from docker hub has issues

### ISSUE THREAD

**Issue by nhanda03** [angelo-v/docker-testinfra#2]
https://hub.docker.com/r/aveltens/docker-testinfra/
image has issues and results in failures for tests which use 

> host.pip_package.get_packages()

Example test which fails .

```
def test_pip_packages(host):
    required_packages = [
        'ansible',
        'ansible-lint',
        'pywinrm',
        'boto',
        'boto3',
        'cryptography',
        'docker'
    ]
    for package in required_packages:
        assert package in host.pip_package.get_packages()

```

Error trace

> docker run --rm -t -v `pwd`:/project \
>         -v /var/run/docker.sock:/var/run/docker.sock:ro \
>         --env IMAGE=testing.jack.com/tools/ansible:`git rev-parse --short HEAD` \
>         aveltens/docker-testinfra
> ====================================================== test session starts =======================================================
> platform linux2 -- Python 2.7.14, pytest-3.5.0, py-1.5.3, pluggy-0.6.0 -- /usr/bin/python2
> cachedir: .pytest_cache
> rootdir: /project, inifile:
> plugins: testinfra-1.11.1
> collected 5 items
> 
> test/test_image.py::test_pip_packages[docker://test_container] FAILED                                                      [ 20%]
> test/test_image.py::test_pip_packages111[docker://test_container] FAILED                                                   [ 40%]
> test/test_image.py::test_molecule_executables[docker://test_container] PASSED                                              [ 60%]
> test/test_image.py::test_swuser[docker://test_container] PASSED                                                            [ 80%]
> test/test_image.py::test_hosts_entry[docker://test_container] PASSED                                                       [100%]
> 
> ============================================================ FAILURES ============================================================
> ___________________________________________ test_pip_packages[docker://test_container] ___________________________________________
> 
> host = <testinfra.host.Host object at 0x7f9d4588af10>
> 
>     def test_pip_packages(host):
>         required_packages = [
>             'ansible',
>             'ansible-lint',
>             'pywinrm',
>             'boto',
>             'boto3',
>             'cryptography',
>             'docker'
>         ]
>         for package in required_packages:
> >           assert package in host.pip_package.get_packages()
> 
> test/test_image.py:37:
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> self = <testinfra.modules.base.PipPackage object at 0x7f9d457fb050>, pip_path = 'pip'
> 
>     def get_packages(self, pip_path="pip"):
>         """Get all installed packages and versions returned by `pip list`:
> 
>             >>> host.pip_package.get_packages(pip_path='~/venv/website/bin/pip')
>             {'Django': {'version': '1.10.2'},
>              'mywebsite': {'version': '1.0a3', 'path': '/srv/website'},
>              'psycopg2': {'version': '2.6.2'}}
>             """
>         output_re = re.compile(r'^(.+) \((.+)\)$')
>         pkgs = {}
>         out = self.check_output("%s list --no-index", pip_path)
>         for line in out.splitlines():
>             if line.startswith('Warning: '):
>                 # Warning: cannot find svn location for rst2pdf==0.93.dev-r0
>                 continue
>             match = output_re.match(line)
>             if match is None:
> >               raise RuntimeError("could not parse {0}".format(repr(line)))
> E               RuntimeError: could not parse u'Package                      Version            '
> 
> /usr/lib/python2.7/site-packages/testinfra/modules/pip.py:41: RuntimeError
> _________________________________________ test_pip_packages111[docker://test_container] __________________________________________
> 
> host = <testinfra.host.Host object at 0x7f9d4588af10>
> 
>     def test_pip_packages111(host):
> >       packages = host.pip_package.get_packages()
> 
> test/test_image.py:40:
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> self = <testinfra.modules.base.PipPackage object at 0x7f9d457fb050>, pip_path = 'pip'
> 
>     def get_packages(self, pip_path="pip"):
>         """Get all installed packages and versions returned by `pip list`:
> 
>             >>> host.pip_package.get_packages(pip_path='~/venv/website/bin/pip')
>             {'Django': {'version': '1.10.2'},
>              'mywebsite': {'version': '1.0a3', 'path': '/srv/website'},
>              'psycopg2': {'version': '2.6.2'}}
>             """
>         output_re = re.compile(r'^(.+) \((.+)\)$')
>         pkgs = {}
>         out = self.check_output("%s list --no-index", pip_path)
>         for line in out.splitlines():
>             if line.startswith('Warning: '):
>                 # Warning: cannot find svn location for rst2pdf==0.93.dev-r0
>                 continue
>             match = output_re.match(line)
>             if match is None:
> >               raise RuntimeError("could not parse {0}".format(repr(line)))
> E               RuntimeError: could not parse u'Package                      Version            '
> 
> /usr/lib/python2.7/site-packages/testinfra/modules/pip.py:41: RuntimeError
> =============================================== 2 failed, 3 passed in 3.94 seconds ===============================================
> make: *** [test] Error 1

Please note that the same works fine if I build a new docker-testinfra image from master in github.

**Comment by angelo-v** [comment]
Since docker hub builds automatically from master, both images should be the same... I hopefully will find time to check this end of the week.

**Comment by angelo-v** [comment]
The test you provided works for me:
`tests/image_test.py::test_pip_packages[docker://jenkins_test_container] PASSED`
* Docker version 18.05.0-ce, build f150324
* aveltens/docker-testinfra image version: sha256:df10b3bd4f650bb28827d5050527be7e5d8be760f255709208fe13c930c80463

If the problem persists for you, please provide me the docker version and image sha256 sum you are using. A repo that allows to reproduce the problem would also be of help.
